import { exec } from "child_process";
import { promisify } from "util";
import type { MeetingInfo } from "./gap-analyzer.js";

const execAsync = promisify(exec);

const OWNER = "danielmeppiel";
const REPO = "corporate-website";

interface EpicIssueResult {
    number: number;
    url: string;
}

export async function createEpicIssue(
    meetingInfo: MeetingInfo,
    requirements: string[],
    onLog?: (message: string) => void,
): Promise<EpicIssueResult> {
    const log = onLog ?? (() => {});
    log("Creating epic issue on GitHub...");
    console.log("[epic-issue] Creating epic issue...");

    const title = `[Epic] ${meetingInfo.title || "Contoso Industries Redesign"}`;

    // Build a markdown table of requirements
    const reqRows = requirements
        .map((r, i) => `| ${i + 1} | ${r.replace(/\|/g, "\\|")} | ⏳ Pending |`)
        .join("\n");

    const bodyParts: string[] = [
        `## 📋 ${meetingInfo.title || "Contoso Industries Redesign"}`,
        "",
    ];

    if (meetingInfo.date) bodyParts.push(`**Date:** ${meetingInfo.date}`);
    if (meetingInfo.participants?.length) {
        bodyParts.push(`**Participants:** ${meetingInfo.participants.join(", ")}`);
    }
    if (meetingInfo.date || meetingInfo.participants?.length) bodyParts.push("");

    if (meetingInfo.summary) {
        bodyParts.push("### Summary", meetingInfo.summary, "");
    }

    bodyParts.push(
        "### Requirements",
        "",
        "| # | Requirement | Status |",
        "|--:|------------|--------|",
        reqRows,
        "",
        "---",
        `*Auto-generated by [Meeting → Code](https://github.com/${OWNER}/meeting-2-code) • ${requirements.length} requirements extracted*`,
    );

    const body = bodyParts.join("\n");

    // Ensure "epic" label exists (create it if not — ignore errors)
    try {
        await execAsync(
            `gh label create epic --description "Epic tracking issue" --color 6f42c1 -R ${OWNER}/${REPO}`,
            { timeout: 10_000, env: { ...process.env, GITHUB_TOKEN: undefined, GH_PAGER: "cat" } },
        );
    } catch {
        // Label may already exist — that's fine
    }

    try {
        const { stdout, stderr } = await execAsync(
            `gh issue create --title ${shellEscape(title)} --body ${shellEscape(body)} --label epic -R ${OWNER}/${REPO}`,
            { timeout: 30_000, env: { ...process.env, GITHUB_TOKEN: undefined, GH_PAGER: "cat" } },
        );

        if (stderr) console.log("[epic-issue] stderr:", stderr.trim());

        const url = stdout.trim();
        const numberMatch = url.match(/\/issues\/(\d+)/);
        const issueNumber = numberMatch ? parseInt(numberMatch[1]!, 10) : 0;

        if (issueNumber > 0) {
            log(`✔ Epic issue #${issueNumber} created`);
            console.log(`[epic-issue] Created #${issueNumber}: ${url}`);
            return { number: issueNumber, url };
        } else {
            log(`⚠ Epic created but unexpected output: ${stdout.substring(0, 100)}`);
            return { number: 0, url: "#" };
        }
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log(`⚠ Failed to create epic: ${msg.substring(0, 150)}`);
        console.error("[epic-issue] Error:", msg);
        // Don't throw — epic is nice-to-have, shouldn't block the flow
        return { number: 0, url: "#" };
    }
}

/**
 * Link individual gap issues as sub-issues of the epic.
 * Uses `gh issue edit --add-sub-issue`.
 */
export async function linkSubIssuesToEpic(
    epicNumber: number,
    subIssueNumbers: number[],
    onLog?: (message: string) => void,
): Promise<void> {
    if (epicNumber <= 0 || subIssueNumbers.length === 0) return;
    const log = onLog ?? (() => {});

    log(`Linking ${subIssueNumbers.length} issues as sub-issues of #${epicNumber}...`);
    console.log(`[epic-issue] Linking ${subIssueNumbers.length} sub-issues to #${epicNumber}...`);

    let linked = 0;
    for (const subNum of subIssueNumbers) {
        if (subNum <= 0) continue;
        try {
            await execAsync(
                `gh issue edit ${epicNumber} --add-sub-issue ${subNum} -R ${OWNER}/${REPO}`,
                { timeout: 15_000, env: { ...process.env, GITHUB_TOKEN: undefined, GH_PAGER: "cat" } },
            );
            linked++;
        } catch (err) {
            // Sub-issue linking may not be available on all plans
            console.error(`[epic-issue] Failed to link #${subNum}:`, err instanceof Error ? err.message : err);
        }
    }
    if (linked > 0) {
        log(`✔ Linked ${linked}/${subIssueNumbers.length} sub-issues to epic #${epicNumber}`);
    } else {
        log(`⚠ Could not link sub-issues (feature may not be available)`);
    }
}

function shellEscape(str: string): string {
    return "'" + str.replace(/'/g, "'\\''") + "'";
}
